#!/usr/bin/env python3
"""Derive `aif-profiled/` from `aif-classic/`.

The same route, the same bridges, the same decisions — plus two things: every
step declares the model profile it wants (`model_profile`, Pri-Fly 0.13.41),
and the plan and implement bridges ask to be run in a session of their own. A
profile names what the step needs from the model, never a product; the host
maps it to a model and an effort, and answers in its report.

    python3 tools/derive_profiled.py          # rewrite aif-profiled/ from aif-classic/
    python3 tools/derive_profiled.py --check  # exit 1 if aif-profiled/ is not what would be written

Components the overlay leaves alone — schemas, decisions, the pinned-skill
pointers, the untouched bridges — are copied byte for byte and keep their ids:
identical bytes under one `id@version` are one component, which is how
`aif-fanout` already shares `aif:context/aif-improve` with `aif-classic`.
Components the overlay changes get their own ids (`aif-profiled:step/verify`)
and their own versions: a derived version starts as the source's and then moves
on its own — its minor is raised whenever the regenerated bytes differ from
what HEAD has, or a derived component it names moved. `test_versions.py` is
the check that this rule was applied, not the rule itself.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "aif-classic"
TARGET = ROOT / "aif-profiled"

# What each step wants from the model. The names are requirements to the work,
# so they survive a change of platform; the host translates them.
PROFILES = {
    "warmup": ("fast-draft", "Warmup reads the project and distils a handoff: breadth and speed, not depth. Its product is a pointer list, not a judgement."),
    "plan": ("deep-reasoning", "The plan is what every later step is judged against, so reasoning is cheapest to spend here; the step runs in a session of its own on the sealed handoff."),
    "improve": ("careful-review", "Improving a plan is reading it against the project and choosing what to take; it needs care rather than invention, and it must not widen the task."),
    "implement": ("deep-reasoning", "Implementation is the Run's real work and, in a long session, its heaviest context; measured on a live Run, a fresh session did it on a fraction of the context with no loss at the gates that followed."),
    "verify": ("careful-review", "A gate's product is a judgement about what the plan promised; it needs care and honesty, and it must look past the diff before it reports anything outside it."),
    "security": ("careful-review", "A security checklist is read against the change and the tree; care over speed, and no writes."),
    "review": ("careful-review", "Review judges the change on its own terms and against the plan; care over speed, and it must look past the diff before it reports anything outside it."),
    "fix": ("deep-reasoning", "Fixing what a gate blocked is implementation under a narrower brief: the blockers, the tree, and nothing else."),
    "commit": ("fast-draft", "Commit reads the tree, removes Run working state and records the head; nothing here needs depth."),
    "continue-improve": ("fast-draft", "One declared question with a closed answer set; the cheapest session that can read the round's result is the right one."),
    "review-challenge": ("independent-review", "A second reader of the change, meant to be a different model than the one that wrote it and to share none of its context; its findings are checked by the review step, so care matters and independence matters more."),
}

# The bridges that ask for a session of their own, and the paragraph that asks.
# The second reviewer's bridge asks for its own session in classic already,
# because independence is what that step is; it is not repeated here.
FRESH_SESSION = {
    "aif-warmup-bridge": "warmup",
    "aif-plan-bridge": "plan",
    "aif-implement-bridge": "implement",
}
FRESH_SESSION_PARAGRAPH = """\
  This step is meant to run in a session of its own. On a host that can start
  one — a subagent, a forked session — start it with the model profile this
  task requests, hand it only this task's `workspace/` (the pinned skill, the
  sealed context, the inputs) and nothing from your own context, let it do the
  step, and submit its report unchanged. Measured on live Runs, a fresh session
  did the heaviest steps on a fraction of the context a long session carries,
  with no loss at the gates that followed, and a small step earns the cheaper
  model its profile names only when it runs apart from the host's own session.
  Answer `model_profile` with the model that session actually ran on; a host
  that cannot start one does the step here and answers `unavailable`, which is
  a true record and not a failure.
"""

# The team's defaults for turning a profile into a model and an effort, per
# host Pri-Fly knows (0.13.43: `model_profiles` in extend.yaml, keyed by the
# hosts the engine knows, not the ones a project declares — a shared package
# has to carry all three). The values are the host's own words; Pri-Fly
# carries them into the task as `model_profile_translation` and reads none of
# them. A developer overrides a whole entry on their machine with
# `project local set --model-profile "HOST NAME key=value"`. fast-draft on
# claude-code is sonnet, not haiku: warmup writes the handoff every later step
# reads, and the first pilot moved it up before a single Run.
MODEL_PROFILES_BLOCK = """\
# How this project turns a step's model profile into a model and an effort,
# per host. Pri-Fly carries the entry into the step's task as
# `model_profile_translation` and reads none of it: the words are the host's
# own. Edit for your team; a developer overrides an entry on their machine
# with `prifly project local set --model-profile "claude-code deep-reasoning model=opus effort=high"`
# (the local entry replaces the whole entry, keys are not merged). A profile
# with no entry for the host you start on travels without a translation, and
# the host answers `unavailable` — a true record, not a failure.
model_profiles:
  claude-code:
    deep-reasoning: {model: opus, effort: high}
    careful-review: {model: opus, effort: medium}
    fast-draft: {model: sonnet, effort: low}
    independent-review: {model: sonnet, effort: medium}
  codex-cli:
    deep-reasoning: {model: gpt-5, reasoning_effort: high}
    careful-review: {model: gpt-5, reasoning_effort: medium}
    fast-draft: {model: gpt-5-mini, reasoning_effort: low}
    independent-review: {model: gpt-5-mini, reasoning_effort: medium}
  codex-app:
    deep-reasoning: {model: gpt-5, reasoning_effort: high}
    careful-review: {model: gpt-5, reasoning_effort: medium}
    fast-draft: {model: gpt-5-mini, reasoning_effort: low}
    independent-review: {model: gpt-5-mini, reasoning_effort: medium}
"""

PACKAGE_TITLE = "AI Factory profiled development workflow"
PACKAGE_DESCRIPTION = "The classic AI Factory route with every step declaring the model profile it wants; plan and implement run in a session of their own."

VERSION_LINE = re.compile(r"^(\s*)version: (\d+)\.(\d+)\.(\d+)$", re.MULTILINE)
PLACEHOLDER = re.compile(r"\{\{(step|workflow|context|schema)_([A-Za-z0-9-]+)\}\}")


def bump_minor(version):
    major, minor, _ = version.split(".")
    return f"{major}.{int(minor) + 1}.0"


def declared_version(text):
    return ".".join(VERSION_LINE.search(text).group(2, 3, 4))


def with_version(text, version):
    # Every `version:` line in the file: a step or bridge has one, the root has
    # two (package and workflow) that are kept equal on purpose.
    return VERSION_LINE.sub(lambda m: f"{m.group(1)}version: {version}", text)


def normalised(text):
    return with_version(text, "0.0.0")


def transform(relative, text):
    """The overlay for one source file, or None for a byte-for-byte copy."""
    parts = relative.parts
    if relative.name == "README.md":
        return None  # written by hand for the derived package
    if parts[0] == "extend.yaml":
        text = text.replace("aif-classic", "aif-profiled")
        # The block goes in after the team's own knobs and before the
        # `extensions` commentary that classic's template ends with.
        marker = "# `extensions` adds a step of your own"
        assert text.count(marker) == 1, "classic's extend.yaml no longer introduces `extensions` where this expects it"
        return text.replace(marker, MODEL_PROFILES_BLOCK + marker)
    if parts[0] == "workflow.yaml":
        text = text.replace("id: aif:package/classic\n", "id: aif-profiled:package/classic\n")
        text = text.replace("id: aif:workflow/classic\n", "id: aif-profiled:workflow/classic\n")
        text = re.sub(r"^  description: .*$", f"  description: {PACKAGE_DESCRIPTION}", text, count=1, flags=re.MULTILINE)
        text = re.sub(r"^title: .*$", f"title: {PACKAGE_TITLE}", text, count=1, flags=re.MULTILINE)
        text = text.replace(".prifly/workflows/aif-classic/", ".prifly/workflows/aif-profiled/")
        return text
    if parts[0] == "workflows":
        return re.sub(r"^id: aif:workflow/([a-z-]+)$", r"id: aif-profiled:workflow/\1", text, count=1, flags=re.MULTILINE)
    if parts[0] == "steps":
        name = relative.stem
        requested, reason = PROFILES[name]
        text = re.sub(r"^id: aif:step/([a-z-]+)$", r"id: aif-profiled:step/\1", text, count=1, flags=re.MULTILINE)
        return text.rstrip("\n") + f"\nmodel_profile:\n  requested: {requested}\n  reason: >-\n    {reason}\n"
    if parts[0] == "contexts" and relative.stem in FRESH_SESSION:
        text = re.sub(r"^id: aif:context/([a-z-]+)$", r"id: aif-profiled:context/\1", text, count=1, flags=re.MULTILINE)
        head, _, rest = text.partition("\n\n")  # the title and the first paragraph, up to the first blank line
        opening, _, rest = rest.partition("\n\n")
        return f"{head}\n\n{opening}\n\n{FRESH_SESSION_PARAGRAPH}\n{rest}"
    return None


def derive():
    """Return {relative path: bytes} for every file of aif-profiled that is generated."""
    sources = sorted(path for path in SOURCE.rglob("*") if path.is_file() and path.name != ".DS_Store")
    # The baseline a version moves from is what the repository last committed,
    # not what is on disk: regenerating five times while a change is worked on
    # must give the same versions as regenerating once.
    committed = committed_target()
    shared, derived = {}, {}
    for path in sources:
        relative = path.relative_to(SOURCE)
        text = path.read_text()
        changed = transform(relative, text)
        if changed is None:
            if relative.name != "README.md":
                shared[relative] = text
        else:
            derived[relative] = changed

    # Versions: derived files move on their own. A file moves when its
    # regenerated bytes differ from what is committed, when a component it
    # names moved (shared ones move with the source), or — for the root — when
    # anything in the package changed at all. Propagation runs to a fixpoint,
    # so the order in which files are visited does not matter.
    versioned = {relative for relative in derived if relative.parts[0] != "extend.yaml"}
    moved = {relative for relative, text in shared.items() if committed.get(relative) not in (None, text)}
    moved |= {relative for relative in versioned if relative in committed and normalised(derived[relative]) != normalised(committed[relative])}
    root = Path("workflow.yaml")
    if root in committed:
        # The package version answers for every byte in the folder: a shared
        # schema that moved with the source is a change here too, even though
        # no derived file names it.
        shared_changed = any(committed.get(other) != text for other, text in shared.items() if other.suffix == ".yaml")
        derived_changed = any(other != root and normalised(text) != normalised(committed.get(other, "")) for other, text in derived.items() if other.suffix == ".yaml")
        if shared_changed or derived_changed:
            moved.add(root)
    while True:
        grown = {relative for relative in versioned if relative in committed and relative not in moved and dependencies(derived[relative]) & moved}
        if not grown:
            break
        moved |= grown
    for relative in versioned:
        if relative not in committed:
            version = declared_version(derived[relative])  # born with the source's version
        elif relative in moved:
            version = bump_minor(declared_version(committed[relative]))
        else:
            version = declared_version(committed[relative])
        derived[relative] = with_version(derived[relative], version)
    files = {relative: text for relative, text in shared.items()}
    files.update(derived)
    return files


def committed_target():
    """aif-profiled as HEAD has it: {relative path: text}, empty before the first commit."""
    import subprocess
    listing = subprocess.run(["git", "-C", str(ROOT), "ls-tree", "-r", "--name-only", "HEAD", TARGET.name], capture_output=True, text=True)
    if listing.returncode != 0:
        return {}
    files = {}
    for line in listing.stdout.splitlines():
        if not line.endswith((".yaml", ".md")):
            continue
        shown = subprocess.run(["git", "-C", str(ROOT), "show", f"HEAD:{line}"], capture_output=True, text=True, check=True)
        files[Path(line).relative_to(TARGET.name)] = shown.stdout
    return files


def dependencies(text):
    out = set()
    for kind, name in PLACEHOLDER.findall(text):
        out.add(Path({"step": "steps", "workflow": "workflows", "context": "contexts", "schema": "schemas"}[kind]) / f"{name}.yaml")
    return out


def main():
    files = derive()
    if "--check" in sys.argv[1:]:
        stale = []
        for relative, text in files.items():
            target = TARGET / relative
            if not target.is_file() or target.read_text() != text:
                stale.append(str(relative))
        extra = [str(p.relative_to(TARGET)) for p in TARGET.rglob("*.yaml") if p.relative_to(TARGET) not in files]
        for name in stale:
            print(f"stale: aif-profiled/{name}")
        for name in extra:
            print(f"not derived from aif-classic: aif-profiled/{name}")
        sys.exit(1 if stale or extra else 0)
    for relative, text in files.items():
        target = TARGET / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text)
    print(f"aif-profiled: {len(files)} files written from aif-classic")


if __name__ == "__main__":
    main()
